server.port=8081

# SQLite Database Configuration
spring.datasource.url=jdbc:sqlite:resume_history.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA/Hibernate Properties
# Use the community dialect to allow Hibernate to speak SQLite syntax
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
